import { Link } from "react-router-dom";
import { MapPin, Brain, Wallet, Clock, Utensils, Hotel, Train, Edit3 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

const featureImages = [
  "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1502920514313-52581002a659?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80",
];

const features = [
  {
    icon: Brain,
    title: "AI-Powered Itineraries",
    description: "Get personalized day-by-day travel plans generated by advanced AI, tailored to your interests and pace.",
    color: "bg-primary/10 text-primary",
    details: {
      highlights: [
        "Day-by-day plan with timings and stops",
        "Interests-based suggestions (nature, food, culture, adventure)",
        "Balanced pacing (relaxed vs packed days)",
        "Practical notes: best time to visit, tips, and alternatives",
      ],
      idealFor: "Travelers who want a complete itinerary fast, without spending hours researching.",
    },
  },
  {
    icon: Wallet,
    title: "Smart Budget Planning",
    description: "Optimized spending with day-wise budget breakdowns. Get the most value without overspending.",
    color: "bg-coral/10 text-coral",
    details: {
      highlights: [
        "Per-day budget split across stay, food, transport, and activities",
        "Cost-saving swaps (free attractions, local eats, off-peak options)",
        "Quick recalculation when budget changes",
        "Transparent estimates so you can plan confidently",
      ],
      idealFor: "Anyone planning with a fixed budget or comparing mid vs premium choices.",
    },
  },
  {
    icon: Clock,
    title: "Optimized Routing",
    description: "Logical place sequencing to minimize travel time. No backtracking — every minute counts.",
    color: "bg-gold/10 text-gold",
    details: {
      highlights: [
        "Clusters nearby places together to reduce commute",
        "Suggests best order for sights within a day",
        "Includes buffer time to keep plans realistic",
        "Great for city trips with many stops",
      ],
      idealFor: "Trips where time matters and you want less zig-zagging across the map.",
    },
  },
  {
    icon: Hotel,
    title: "Stay Suggestions",
    description: "Budget, mid-range, and luxury accommodation options near your planned attractions.",
    color: "bg-primary/10 text-primary",
    details: {
      highlights: [
        "Stay options near your day-wise itinerary",
        "Area guidance: safer/better connected neighborhoods",
        "Choices across budget ranges",
        "Optimized for shorter commutes",
      ],
      idealFor: "Travelers who want to pick a stay location that fits the itinerary (not the other way around).",
    },
  },
  {
    icon: Utensils,
    title: "Local Food & Culture",
    description: "Discover local dishes, hidden cafes, and authentic cultural experiences at every stop.",
    color: "bg-coral/10 text-coral",
    details: {
      highlights: [
        "Must-try local dishes and where to find them",
        "Cultural etiquette tips and local customs",
        "Hidden gems beyond tourist traps",
        "Festival/seasonal suggestions (when relevant)",
      ],
      idealFor: "Food lovers and culture-first travelers.",
    },
  },
  {
    icon: Train,
    title: "Transport Options",
    description: "Local and intercity transport suggestions with estimated costs for hassle-free travel.",
    color: "bg-gold/10 text-gold",
    details: {
      highlights: [
        "Local transit recommendations (metro/bus/ride-share)",
        "Intercity options (train/flight/bus) when applicable",
        "Estimated costs and time tradeoffs",
        "Practical tips for tickets and peak hours",
      ],
      idealFor: "Trips with multiple cities or travelers who prefer planning logistics upfront.",
    },
  },
  {
    icon: Edit3,
    title: "Fully Customizable",
    description: "Edit any activity, swap places, add notes. Changed your budget? Only affected sections regenerate.",
    color: "bg-primary/10 text-primary",
    details: {
      highlights: [
        "Swap activities without breaking the whole plan",
        "Add your own notes and preferences",
        "Regenerate only the part that changed",
        "Keep control while still saving time",
      ],
      idealFor: "People who want a smart starting point but still like to tweak the plan.",
    },
  },
  {
    icon: MapPin,
    title: "Share & Export",
    description: "Share your itinerary via link, download as PDF, or email it — even to your travel buddies.",
    color: "bg-coral/10 text-coral",
    details: {
      highlights: [
        "Shareable itinerary link",
        "Easy to forward to friends/family",
        "Great for group trips and approvals",
        "Keep everything in one place",
      ],
      idealFor: "Group trips, family vacations, or anyone coordinating plans with others.",
    },
  },
];

const FeaturesSection = () => {
  return (
    <section className="py-20 lg:py-28 bg-gradient-section">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <span className="inline-block text-sm font-semibold text-coral uppercase tracking-wider mb-3">
            Features
          </span>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-display font-bold text-foreground mb-4">
            Everything You Need to{" "}
            <span className="text-primary">Plan Smarter</span>
          </h2>
          <p className="text-muted-foreground text-lg leading-relaxed">
            From AI-generated itineraries to budget optimization, Travearth handles the complexity so you can focus on the adventure.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <Dialog key={feature.title}>
              <DialogTrigger asChild>
                <button
                  type="button"
                  className="fade-up group p-6 rounded-2xl bg-card border border-border/50 hover:shadow-travel hover:border-primary/20 transition-all duration-500 ease-out hover:-translate-y-1 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                  aria-label={`Open details for ${feature.title}`}
                >
                  {/* ✅ IMAGE FIXED */}
                  <div className="w-full h-40 overflow-hidden rounded-t-2xl mb-4">
                    <img
                      src={featureImages[index]}
                      alt={feature.title}
                      className="w-full h-full object-cover transition-transform duration-500 ease-out group-hover:scale-105"
                      loading="lazy"
                    />
                  </div>

                  <div className={`w-12 h-12 rounded-xl ${feature.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                    <feature.icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-lg font-semibold text-foreground mb-2 font-sans">
                    {feature.title}
                  </h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {feature.description}
                  </p>
                  <span className="mt-4 inline-block text-sm font-medium text-primary">
                    Learn more →
                  </span>
                </button>
              </DialogTrigger>

              <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <div className="flex items-start gap-3">
                    <div className={`mt-0.5 w-10 h-10 rounded-xl ${feature.color} flex items-center justify-center`}>
                      <feature.icon className="w-5 h-5" />
                    </div>
                    <div className="space-y-1">
                      <DialogTitle>{feature.title}</DialogTitle>
                      <DialogDescription>{feature.description}</DialogDescription>
                    </div>
                  </div>
                </DialogHeader>

                <div className="rounded-xl overflow-hidden border border-border/50">
                  <img
                    src={featureImages[index]}
                    alt={feature.title}
                    className="h-48 w-full object-cover"
                    loading="lazy"
                  />
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-semibold text-foreground">What you’ll get</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                    {feature.details.highlights.map((item: string) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-xl border border-border/50 bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">
                    <span className="font-medium text-foreground">Ideal for:</span> {feature.details.idealFor}
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row gap-3 sm:justify-end">
                  <Link to="/plan">
                    <Button className="w-full sm:w-auto">Try it on your trip</Button>
                  </Link>
                  <Link to="/contact">
                    <Button variant="outline" className="w-full sm:w-auto">Ask a question</Button>
                  </Link>
                </div>
              </DialogContent>
            </Dialog>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
