import { MapPin, Brain, Wallet, Clock, Utensils, Hotel, Train, Edit3 } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Itineraries",
    description: "Get personalized day-by-day travel plans generated by advanced AI, tailored to your interests and pace.",
    color: "bg-primary/10 text-primary",
  },
  {
    icon: Wallet,
    title: "Smart Budget Planning",
    description: "Optimized spending with day-wise budget breakdowns. Get the most value without overspending.",
    color: "bg-coral/10 text-coral",
  },
  {
    icon: Clock,
    title: "Optimized Routing",
    description: "Logical place sequencing to minimize travel time. No backtracking — every minute counts.",
    color: "bg-gold/10 text-gold",
  },
  {
    icon: Hotel,
    title: "Stay Suggestions",
    description: "Budget, mid-range, and luxury accommodation options near your planned attractions.",
    color: "bg-primary/10 text-primary",
  },
  {
    icon: Utensils,
    title: "Local Food & Culture",
    description: "Discover local dishes, hidden cafes, and authentic cultural experiences at every stop.",
    color: "bg-coral/10 text-coral",
  },
  {
    icon: Train,
    title: "Transport Options",
    description: "Local and intercity transport suggestions with estimated costs for hassle-free travel.",
    color: "bg-gold/10 text-gold",
  },
  {
    icon: Edit3,
    title: "Fully Customizable",
    description: "Edit any activity, swap places, add notes. Changed your budget? Only affected sections regenerate.",
    color: "bg-primary/10 text-primary",
  },
  {
    icon: MapPin,
    title: "Share & Export",
    description: "Share your itinerary via link, download as PDF, or email it — even to your travel buddies.",
    color: "bg-coral/10 text-coral",
  },
];

const container = {
  hidden: {},
  show: {
    transition: { staggerChildren: 0.08 },
  },
};

const item = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

const FeaturesSection = () => {
  return (
    <section className="py-20 lg:py-28 bg-gradient-section">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <span className="inline-block text-sm font-semibold text-coral uppercase tracking-wider mb-3">
            Features
          </span>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-display font-bold text-foreground mb-4">
            Everything You Need to{" "}
            <span className="text-primary">Plan Smarter</span>
          </h2>
          <p className="text-muted-foreground text-lg leading-relaxed">
            From AI-generated itineraries to budget optimization, Travearth handles the complexity so you can focus on the adventure.
          </p>
        </div>

        {/* Grid */}
        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-100px" }}
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
        >
          {features.map((feature) => (
            <motion.div
              key={feature.title}
              variants={item}
              className="group p-6 rounded-2xl bg-card border border-border/50 hover:shadow-travel hover:border-primary/20 transition-all duration-300"
            >
              <div className={`w-12 h-12 rounded-xl ${feature.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                <feature.icon className="w-6 h-6" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2 font-sans">
                {feature.title}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default FeaturesSection;
